### ISSUE TITLE
ошибка SafeMySQL

### ISSUE THREAD

**Issue by mrYamakasi** [dle-modules/DLE-Faker#1]
PHP/5.5.30

почему то не пашет на локалке пробую на 10,6
изначально запустил инсталер ругается на:
Notice: Undefined variable: config in \www\dle106\engine\api\api.class.php on line 628

Notice: Array to string conversion in \www\dle106\faker_install.php on line 202

Notice: Undefined variable: installForm in \www\dle106\faker_install.php on line 177

ну и после добавления хоть 1 новость, то выходит такое:
Fatal error: Uncaught exception 'Exception' with message 'SafeMySQL: Field 'xfields' doesn't have a default value. Full query: [INSERT INTO dle_post SET autor='admin', date='2015-10-27 21:16:43', title='Этим обед и вечер к полицеймейстеру, где с.', alt_name='etim-obed-i-vecher-k-policeymeysteru-gde-s', short_story='\"Этим 
Изволь, едем, — сказал еще раз взглянул на него искоса, когда проходили они столовую: медведь! соверше� in \www\dle106\engine\modules\faker\classes\SafeMySQL.php on line 632

**Comment by pafnuty** [comment]
`Field 'xfields' doesn't have a default value` - говорит, что допполе не имеет значения по умолчанию.
https://github.com/dle-modules/DLE-Faker/blob/master/upload/engine/modules/faker/admin/main.php#L389 вот эта строка случаем не раскомменчена?
Я не делал добавление допполей.

DLE UTF?

**Comment by mrYamakasi** [comment]
скачивал отсюда, в коде где указали также как у Вас тут // $arFaker[$ii]['xfields']     = '';
то есть закоментирована строчка

дам стоит на локалке UTF

**Comment by pafnuty** [comment]
В DLE вносили правки?

**Comment by mrYamakasi** [comment]
нет, чистая как бы))

**Comment by pafnuty** [comment]
Попробую как-нибудь воспроизвести ошибку.

**Comment by pafnuty** [comment]
Так и не удалось воспроизвести ошибку.
