### ISSUE TITLE
 возможность назначить допполе для картинки

### ISSUE THREAD

**Issue by be2clack** [dle-modules/DLE-Faker#3]
возможность назначить допполе для картинки

**Comment by pafnuty** [comment]
такой возможности пока нет

**Comment by be2clack** [comment]
ну я понял что нет, но ты написал в комментариях. Чтоб написали тут в тикет, и потом сделаешь...

**Comment by pafnuty** [comment]
Вот [примерно так](https://github.com/dle-modules/DLE-Faker/issues/4) нужно описывать свои желания.
